name: loan-oa
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - cpuonly
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip:
      - joblib
      - tqdm
      